version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./tmp:/tmp/docx2pdf
    environment:
      - PORT=8080
      - MAX_FILE_SIZE=10485760  # 10MB
      - TEMP_DIR=/tmp/docx2pdf
    restart: unless-stopped 