version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      API_TOKEN: ${API_TOKEN}
      PORT: 3000
    volumes:
      - ./data:/app/data
